name: lemur
channels:
  - cadquery
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.8.3=py310h80987f9_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - ampl-mp=3.1.0=h21a7fc1_1005
  - aom=3.5.0=h7ea286d_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - appnope=0.1.2=py310hca03da5_1001
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.2=py310hca03da5_0
  - attrs=22.1.0=py310hca03da5_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - brotlipy=0.7.0=py310h1a28f6b_1002
  - bzip2=1.0.8=h620ffc9_4
  - c-ares=1.19.0=h80987f9_0
  - ca-certificates=2023.05.30=hca03da5_0
  - cadquery=master=2.3.1_15_g1257622
  - casadi=3.6.3=py310h8910d8e_0
  - certifi=2023.5.7=py310hca03da5_0
  - cffi=1.15.1=py310h80987f9_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - comm=0.1.2=py310hca03da5_0
  - cryptography=39.0.1=py310h834c97f_2
  - curl=8.1.1=h80987f9_1
  - debugpy=1.5.1=py310hc377ac9_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - double-conversion=3.2.0=hb7217d7_1
  - eigen=3.3.7=h525c30c_1
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.5.0=hb7217d7_1
  - ezdxf=1.0.3=py310h2887b22_0
  - ffmpeg=5.1.2=gpl_hf318d42_106
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.2=h82840c6_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - freeimage=3.18.0=ha6e172d_12
  - freetype=2.12.1=h1192e45_0
  - frozenlist=1.3.3=py310h80987f9_0
  - gettext=0.21.1=h0186832_0
  - gl2ps=1.4.2=h1192e45_1
  - glew=2.1.0=hc377ac9_3
  - glib=2.76.4=ha614eb4_0
  - glib-tools=2.76.4=ha614eb4_0
  - gmp=6.2.1=hc377ac9_3
  - gnutls=3.7.8=h9f1a10d_0
  - gst-plugins-base=1.22.3=h514c7bf_0
  - gstreamer=1.22.3=h80987f9_0
  - hdf4=4.2.15=h1a38d6a_5
  - hdf5=1.12.2=nompi_ha7af310_101
  - icu=70.1=h6b3803e_0
  - idna=3.4=py310hca03da5_0
  - imath=3.1.6=hb5ab8b9_1
  - ipopt=3.14.12=h843a782_0
  - ipykernel=6.19.2=py310h33ce5c2_0
  - ipython=8.12.0=py310hca03da5_0
  - jedi=0.18.1=py310hca03da5_1
  - jpeg=9e=h80987f9_1
  - jsoncpp=1.9.5=hc021e02_1
  - jupyter_client=8.1.0=py310hca03da5_0
  - jupyter_core=5.3.0=py310hca03da5_0
  - jxrlib=1.1=h1a28f6b_2
  - krb5=1.20.1=hf3e1bf2_1
  - lame=3.100=h1a28f6b_0
  - lcms2=2.15=h481adae_0
  - lerc=3.0=hc377ac9_0
  - libaec=1.0.6=hb7217d7_1
  - libblas=3.9.0=17_osxarm64_openblas
  - libcblas=3.9.0=17_osxarm64_openblas
  - libclang=14.0.6=default_h1b80db6_1
  - libclang13=14.0.6=default_h24352ff_1
  - libcurl=8.1.1=h3e2b118_1
  - libcxx=16.0.6=h4653b0c_0
  - libdeflate=1.17=h80987f9_0
  - libedit=3.1.20221030=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libexpat=2.5.0=hb7217d7_1
  - libffi=3.4.4=hca03da5_0
  - libgfortran=5.0.0=12_2_0_hd922786_31
  - libgfortran5=12.2.0=h0eea778_31
  - libglib=2.76.4=h24e9cb9_0
  - libiconv=1.17=he4db4b2_0
  - libidn2=2.3.4=h80987f9_0
  - liblapack=3.9.0=17_osxarm64_openblas
  - libllvm14=14.0.6=h7ec7a93_3
  - libnetcdf=4.9.1=nompi_h232cb48_101
  - libnghttp2=1.52.0=h62f6fdd_1
  - libogg=1.3.5=h1a28f6b_1
  - libopenblas=0.3.23=openmp_hc731615_0
  - libopus=1.3.1=h27ca646_1
  - libosqp=0.6.3=h313beb8_0
  - libpng=1.6.39=h80987f9_0
  - libpq=15.3=h7126958_1
  - libqdldl=0.1.7=h313beb8_0
  - libraw=0.21.1=h1a38d6a_0
  - libsodium=1.0.18=h1a28f6b_0
  - libsqlite=3.42.0=hb31c410_0
  - libssh2=1.10.0=h02f6b3c_2
  - libtasn1=4.19.0=h80987f9_0
  - libtheora=1.1.1=h1a28f6b_3
  - libtiff=4.5.0=h313beb8_2
  - libunistring=0.9.10=h1a28f6b_0
  - libvorbis=1.3.7=h1a28f6b_0
  - libvpx=1.11.0=hc377ac9_0
  - libwebp-base=1.2.4=h80987f9_1
  - libxml2=2.10.3=h67585b2_4
  - libzip=1.9.2=h76ab92c_1
  - libzlib=1.2.13=h53f4e23_5
  - llvm-openmp=14.0.6=hc6e5704_0
  - loguru=0.5.3=py310hca03da5_4
  - lz4-c=1.9.4=h313beb8_0
  - matplotlib-inline=0.1.6=py310hca03da5_0
  - metis=5.1.0=hc377ac9_0
  - multidict=6.0.2=py310h1a28f6b_0
  - multimethod=1.9.1=py310hca03da5_0
  - mumps-include=5.2.1=hce30654_11
  - mumps-seq=5.2.1=h0066fe1_11
  - mysql-common=8.0.33=h7b5afe1_1
  - mysql-libs=8.0.33=hb292caa_1
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.5.6=py310hca03da5_0
  - nettle=3.8.1=h63371fa_1
  - nlohmann_json=3.11.2=h313beb8_0
  - nlopt=2.7.1=py310heaf8407_3
  - nptyping=2.5.0=pyhd8ed1ab_0
  - nspr=4.35=h313beb8_0
  - nss=3.89.1=h313beb8_0
  - numpy=1.25.1=py310haa1e00c_0
  - occt=7.7.0=hafc16cd_2
  - ocp=7.7.0.1=py310h1798ea7_0
  - openexr=3.1.5=h25aad90_2
  - openh264=2.3.1=hb7217d7_2
  - openjpeg=2.5.0=hbc2ba62_2
  - openssl=3.1.1=h53f4e23_1
  - p11-kit=0.24.1=h29577a5_0
  - packaging=23.0=py310hca03da5_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre2=10.40=hb34f9b4_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=23.1.2=py310hca03da5_0
  - platformdirs=2.5.2=py310hca03da5_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - proj=9.1.1=h13f728c_2
  - prompt-toolkit=3.0.36=py310hca03da5_0
  - proxsuite=0.3.7=py310h38f39d4_0
  - psutil=5.9.0=py310h1a28f6b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pugixml=1.11.4=hc377ac9_1
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py310hca03da5_1
  - pyopenssl=23.0.0=py310hca03da5_0
  - pyparsing=3.0.9=py310hca03da5_0
  - pysocks=1.7.1=py310hca03da5_0
  - python=3.10.12=h01493a6_0_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.10=3_cp310
  - pyzmq=25.1.0=py310h313beb8_0
  - qt-main=5.15.8=hfe8d25c_6
  - rapidjson=1.1.0=h525c30c_0
  - readline=8.2=h1a28f6b_0
  - requests=2.29.0=py310hca03da5_0
  - scipy=1.11.1=py310h0975f3d_0
  - scotch=6.0.9=hc7b06cf_1
  - setuptools=67.8.0=py310hca03da5_0
  - simde=0.7.6=h1995070_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h80987f9_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - svt-av1=1.4.1=h7ea286d_0
  - tbb=2021.8.0=h48ca7d4_0
  - tbb-devel=2021.8.0=h48ca7d4_0
  - tinyxml2=9.0.0=hbdafb3b_2
  - tk=8.6.12=hb8d0fd4_0
  - tornado=6.2=py310h1a28f6b_0
  - traitlets=5.7.1=py310hca03da5_0
  - typing_extensions=4.6.3=py310hca03da5_0
  - typish=1.9.3=pyhd8ed1ab_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.16=py310hca03da5_0
  - utfcpp=3.2.1=hca03da5_0
  - vtk=9.2.5=qt_py310h87518ef_203
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.38.4=py310hca03da5_0
  - wslink=1.11.1=pyhd8ed1ab_0
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xz=5.4.2=h80987f9_0
  - yarl=1.8.1=py310h1a28f6b_0
  - zeromq=4.3.4=hc377ac9_0
  - zlib=1.2.13=h53f4e23_5
  - zstd=1.5.5=hd90d995_0
  - pip:
      - annotated-types==0.5.0
      - anyio==3.7.1
      - anytree==2.9.0
      - blinker==1.6.2
      - build123d==0.1.dev873+g8d2c541
      - cachetools==5.2.0
      - click==8.1.6
      - cmake==3.26.4
      - dnspython==2.4.0
      - email-validator==2.0.0.post2
      - exceptiongroup==1.1.2
      - fastapi==0.100.0
      - h11==0.14.0
      - httpcore==0.17.3
      - httptools==0.6.0
      - httpx==0.24.1
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - markupsafe==2.1.3
      - numpy-quaternion==2022.4.3
      - numpy-stl==3.0.1
      - ocp-tessellate==1.1.2
      - ocp-vscode==1.2.2
      - orjson==3.9.2
      - pydantic==2.1.0
      - pydantic-core==2.4.0
      - pydantic-extra-types==2.0.0
      - pydantic-settings==2.0.2
      - python-dotenv==1.0.0
      - python-multipart==0.0.6
      - python-utils==3.7.0
      - pyyaml==6.0.1
      - sniffio==1.3.0
      - starlette==0.27.0
      - svgpathtools==1.6.1
      - svgwrite==1.4.3
      - ujson==5.8.0
      - uvicorn==0.23.1
      - uvloop==0.17.0
      - watchfiles==0.19.0
      - webcolors==1.12
      - websockets==11.0.3
      - werkzeug==2.3.6
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/lemur
